# Generated by Django 4.2 on 2023-05-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
