# Generated by Django 4.2 on 2023-05-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_blog_image_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/blog/default_image.jpeg', null=True, upload_to='blog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.blog')),
            ],
        ),
    ]
