# Generated by Django 4.2 on 2023-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0011_remove_blog_image_alter_blog_id_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(default='media/blog/default_image.jpeg', null=True, upload_to='blog'),
        ),
    ]
