# Generated by Django 4.2 on 2023-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_alter_blog_options_blog_pinned_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pinned_order',
        ),
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
