# Generated by Django 4.2 on 2023-05-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_alter_blog_options_remove_blog_pinned_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pinned',
        ),
    ]
