# Generated by Django 4.2 on 2023-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0020_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(default='media/blog/default_image.jpg', upload_to='blog'),
        ),
    ]
