# Generated by Django 4.2 on 2023-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0021_alter_blogimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
