# Generated by Django 4.2 on 2023-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0022_blog_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pinned',
        ),
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.ManyToManyField(blank=True, related_name='pinned_to', to='firstApp.blog'),
        ),
    ]
