# Generated by Django 4.2 on 2023-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0023_remove_blog_pinned_blog_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pinned_order', '-created']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pinned',
        ),
        migrations.AddField(
            model_name='blog',
            name='pinned_order',
            field=models.IntegerField(default=0),
        ),
    ]
